name: BingoMC
version: 1.0.0-SNAPSHOT
main: com.hairo.bingomc.BingoMC
api-version: "1.21"
author: Hairo
dependencies:
  server:
    Multiverse-Core:
      load: BEFORE
      required: true
    Multiverse-NetherPortals:
      load: BEFORE
      required: true
    Multiverse-Inventories:
      load: BEFORE
      required: true
permissions:
  bingomc.goals.user:
    description: Allows opening the goals UI and viewing goals
    default: not op
  bingomc.goals.admin:
    description: Allows opening the goals admin UI and managing goals
    default: op
  bingomc.goals.reload:
    description: Allows reloading goals
    default: op
  bingomc.goals.validate:
    description: Allows validating goals
    default: op
  bingomc.start:
    description: Allows starting a Bingo round
    default: op
  bingomc.stop:
    description: Allows stopping a Bingo round
    default: op
  bingomc.export:
    description: Allows exporting possible goal configuration options
    default: op
